spring.datasource.url=jdbc:mysql://localhost:3306/EventZen?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

event.jwt.secret=eventzen-super-secret-key-this-is-just-for-development

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs