spring.application.name=bookingservice

spring.datasource.url=jdbc:mysql://mysql:3306/eventzen
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

event.service.base-url=http://event-service:8080

# Must match the user service signing key
security.jwt.secret=eventzen-super-secret-key-this-is-just-for-development

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.initializationFailTimeout=60000
